export enum HISTORY_ACTIONS {
	SELECT = 'select',
	BRUSH = 'brush',
	RECTANGLE = 'rectangle',
	CIRCLE = 'circle',
	ERASER = 'eraser',
	TEXT = 'text',
	LINE = 'line',
	UNDO = 'undo',
	REDO = 'redo',
	LAYER_ADD = 'add',
	LAYER_CLEAR = 'clear',
	LAYER_DELETE = 'delete',
	LAYER_OPACITY = 'opacity',
	LAYER_RENAME = 'rename',
	LAYER_ACTIVE = 'active',
	LAYER_ORDER = 'order',
	LAYER_HIDE = 'hide',
}
